### ISSUE TITLE
Conflicting parameter in Healthcheck

### ISSUE THREAD

**Issue by Freekers** [Lonsofore/cod2docker#1]
First of all, thank you very much for this Docker image. It greatly reduces the time needed to setup libcod.

I've noticed there is a conflicting parameter in the Healthcheck. The netcat command executed for the Healthcheck contains a `-w 1` parameter, indicating that netcat should close the connection after 1 second if the connection is idle. This conflicts with the `--timeout=3s` parameter of the Healthcheck command. After all, the nc command will always be terminated after 1 second, so the 3 second timeout will never be met.

This is particularly an issue during map changes, as the netcat command will take longer to resolve. The container will be marked unhealthy after 3 retries and restarted using the willfarell/autoheal image, which has caused multiple reboots of my COD2 server instance while it was perfectly healthy. It was simply loading the next map. So my first instinct was to raise the `--retries` and `-w` value a little bit, but boy did I go down the rabbit hole....

First off, it looks like netcat (nc) ignores any other value for the timeout `-w` parameter than 1... Example:
```
root@COD:/cod2# time echo -e '\xff\xff\xff\xffgetinfo' | nc -w **3** -u ${CHECK_IP} ${CHECK_PORT}
����infoResponse
\protocol\115\hostname\^3Server^1#1\mapname\mp_breakout\sv_maxclients\14\gametype\tdm\pure\1\maxPing\300\con_disabled\1\kc\1\hw\1\mod\1\voice\0
real    **0m6.013s**
user    0m0.001s
sys     0m0.007s
```
As you can see, the netcat command took 6 seconds to executes whereas I specifically said it to timeout after 3 seconds.... `¯\_(ツ)_/¯`

So I figured I could use `timeout 3 nc ...` as workaround, like so:
```
root@COD:/cod2# time echo -e '\xff\xff\xff\xffgetinfo' | timeout 3 nc -u ${CHECK_IP} ${CHECK_PORT}
����infoResponse
\protocol\115\hostname\^3Server^1#1\mapname\mp_breakout\sv_maxclients\14\gametype\tdm\pure\1\maxPing\300\con_disabled\1\kc\1\hw\1\mod\1\voice\0

real    **0m3.005s**
user    0m0.002s
sys     0m0.007s
```
At a first glance this seems to be doing what we want, but upon further investigation I found out that using `timeout` in conjunction with nc, the exit code would always be 124, no matter if the 'getinfo' command completed successfully or not...

Hence I swapped nc for ncat, which is the version of netcat from the Nmap Project, which exits immediately as soon it's connected to the desired IP and port. Hence no timeout parameter for ncat is needed anymore.... but as it turns out, ncat doesn't play nice with being run inside a Docker container. I haven't been able to figure out why, but ncat intermittently worked. Often it would close the connection immediately without sending the getinfo packet, whereas sometimes it would work just fine... using the same command.

I finally resorted to socat. Socat also exits immediately as soon it's connected to the desired IP and port and seems to do just what we need. It's syntax looks as follows: 
`socat - udp:${CHECK_IP}:${CHECK_PORT})`

I hope this helps. Perhaps you can incorporate in your Healthcheck.

**Comment by Lonsofore** [comment]
Thank you for your issue and detailed research!

First of all, there is no conflict in Docker healthcheck timeout and -w arg in nc. When you execute nc - it always takes more than -w time, so healthcheck timeout is just for full command, with echo, nc, if, etc.

I also tried to use different -w args and it works well on my Ubuntu (and in Ubuntu Docker image as well):

> 
> ~ time echo -e '\xff\xff\xff\xffgetinfo' | nc -w1 -u 185.211.247.23 28960
> ����infoResponse
> \protocol\115\hostname\Cracked^5Vodka^7^7 | Version 1.0! | Maps: cod2.ru/maps\mapname\mp_toujane\clients\29\sv_maxclients\45\gametype\ctf\pure\1\maxPing\350\game\rusvodka\kc\1\hw\1\mod\1\voice\0echo -e '\xff\xff\xff\xffgetinfo'  0,00s user 0,00s system 44% cpu 0,001 total
> nc -w1 -u 185.211.247.23 28960  0,00s user 0,00s system 0% cpu 1,029 total

> 
> ~ time echo -e '\xff\xff\xff\xffgetinfo' | nc -w3 -u 185.211.247.23 28960
> ����infoResponse
> \protocol\115\hostname\Cracked^5Vodka^7^7 | Version 1.0! | Maps: cod2.ru/maps\mapname\mp_toujane\clients\30\sv_maxclients\45\gametype\ctf\pure\1\maxPing\350\game\rusvodka\kc\1\hw\1\mod\1\voice\0echo -e '\xff\xff\xff\xffgetinfo'  0,00s user 0,00s system 51% cpu 0,001 total
> nc -w3 -u 185.211.247.23 28960  0,00s user 0,00s system 0% cpu 3,029 total

Now let's think about -w time size. 1 second - is it enough? I think yes, because we're trying to access localhost, in the same container. The problem is - sometimes, on map restart, we can get false-negative healthcheck and restart the server after 3 false-negative healthchecks in a row. So, we can just extend --retries flag to 5, for example. It would give about 15 more seconds for map restart (because there are 5 seconds between healthchecks). By the way, my server works about 2 weeks without restarts, so it may depend on your modifications. Anyway, this is a problem and I'll make a PR for this.

And thank you for your attention, I'm happy that you use it :)

**Comment by Lonsofore** [comment]
So, [here](https://github.com/Lonsofore/cod2docker/commit/d3504effb4acb1c4d3f118e5a4be8c3c6c184922) is an update with some fixes. Already on [Docker Hub](https://hub.docker.com/r/lonsofore/cod2).

@Freekers, can you try it on your server? I changed --retries from 3 to 7.

**Comment by Freekers** [comment]
Apologies for the delayed reply. I encountered no more issues now.
Thank you :) !
